spring:
  flyway:
    enabled: true
  profiles:
    active: prod

management:
  server:
    port: 8082

#logging
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
telegram:
  type:
  token:
