create table if not exists channel_group_bind
(
    id         int    not null generated by default as identity primary key,
    channel_id bigint not null,
    group_id   bigint not null
);

create unique index if not exists ui_channel_group_bind
    on channel_group_bind (channel_id);

create table if not exists channel_available_users
(
    id         int    not null generated by default as identity primary key,
    channel_id bigint not null,
    user_id    bigint not null,
    username   varchar(255)
);

create unique index if not exists ui_channel_users
    on channel_available_users (channel_id, user_id);

create table if not exists channel_topic_users
(
    id         int    not null generated by default as identity primary key,
    user_id    bigint not null,
    topic_id   bigint not null,
    channel_id bigint not null
);

create unique index if not exists ui_group_topic_users
    on channel_topic_users (channel_id, topic_id, user_id);

create table if not exists channel_topics
(
    id               int    not null generated by default as identity primary key,
    channel_id       bigint not null,
    channel_tread_id bigint not null,
    group_thread_id  bigint not null
);

create unique index if not exists ui_channel_topics
    on channel_topics (channel_id, group_thread_id);

create table if not exists user_history
(
    id                             int    not null generated by default as identity primary key,
    user_id                        bigint not null,
    channel_id                     bigint not null,
    topic_id                       int    not null,
    first_notification_message_id  int,
    first_original_message_id      int,
    second_notification_message_id int,
    second_original_message_id     int,
    third_notification_message_id  int,
    third_original_message_id      int
);

create unique index if not exists ui_user_history
    on user_history (user_id);